function update() {
  $("#version").text(version);
  $("#money").text(stats.money.toFixed(2));
  $("#moneysec").text(stats.moneysec.toFixed(2));
  $("#totalxp").text(stats.xp);
  $("#level").text(stats.lvl);
  $("#stats_exp_to_next_level").html(stats.lvlxp + stats.totalxp - Math.floor(stats.xp));
  $("#experience").attr("value", stats.xp - stats.totalxp);
  $("#experience").attr("max", stats.lvlxp);
  $("#costfasterlaptops").text(upgrades.fasterlaptops.cost.toFixed(2));
  $("#amountfasterlaptops").text(upgrades.fasterlaptops.amount);
  $("#costcatcoinminer").text(upgrades.catcoinminer.cost.toFixed(2));
  $("#amountcatcoinminer").text(upgrades.catcoinminer.amount);
  $(".namebedpurple").each(function(){$(this).text(items.bedpurple.name)});
  $(".costbedpurple").each(function(){$(this).text(items.bedpurple.cost)});
  $(".descbedpurple").each(function(){$(this).text(items.bedpurple.desc)});
  $(".namedronebat").each(function(){$(this).text(items.dronebat.name)});
  $(".costdronebat").each(function(){$(this).text(items.dronebat.cost)});
  $(".descdronebat").each(function(){$(this).text(items.dronebat.desc)});
  $(".namehairwhite").each(function(){$(this).text(items.hairwhite.name)});
  $(".costhairwhite").each(function(){$(this).text(items.hairwhite.cost)});
  $(".deschairwhite").each(function(){$(this).text(items.hairwhite.desc)});
};
